# Local Netlify development
[dev]
framework = "#static"
command = "npm run dev"

# Build step
[build]
command = "npm run build"
publish = "_site"

  [build.processing]
  skip_processing = true

  [build.environment]
  NODE_VERSION = "16"

# I'm a Teapot
[[redirects]]
from = "/brew/"
to = "/.netlify/functions/teapot"
status = 200
force = true
_generated_by_eleventy_serverless = "teapot"

# ListenBrainz music stats
[[redirects]]
from = "/music/stats/"
to = "/.netlify/builders/ondemand"
status = 200
force = true
_generated_by_eleventy_serverless = "ondemand"

# From Netlify base domain
[[redirects]]
from = "https://troyvassalotti.netlify.com/*"
to = "https://www.troyv.dev/:splat"
status = 301
force = true

# Fediverse discovery
[[redirects]]
from = "/.well-known/webfinger"
to = "https://fosstodon.org/.well-known/webfinger?resource=acct:rest@fosstodon.org"
status = 200

# HTTP headers
[[headers]]
for = "/*"

  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1"

# Cache assets for future builds
[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ "_cache" ]
