[dev]
framework = "#static"
command = "npm run dev"

[build]
command = "npm run build"
publish = "_site"

  [build.processing]
  skip_processing = true

  [build.environment]
  NODE_VERSION = "18"

[[redirects]]
from = "/music/stats/"
to = "/.netlify/builders/ondemand"
status = 200
force = true
_generated_by_eleventy_serverless = "ondemand"

[[redirects]]
from = "/brew/"
to = "/.netlify/functions/teapot"
status = 200
force = true
_generated_by_eleventy_serverless = "teapot"

[[redirects]]
from = "https://troyvassalotti.netlify.com/*"
to = "https://www.troyv.dev/:splat"
status = 301
force = true

[[redirects]]
from = "/.well-known/webfinger"
to = "https://fosstodon.org/.well-known/webfinger?resource=acct:rest@fosstodon.org"
status = 200

[[headers]]
for = "/*"

  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ "_cache" ]

[[plugins]]
package = "netlify-plugin-webmentions"

[functions]
directory = "netlify/functions/"
node_bundler = "zisi"
