[dev]
framework = "#static"
command = "npm run dev"

[build]
command = "npm run build"
publish = "_site"

  [build.processing]
  skip_processing = true

  [build.environment]
  NODE_VERSION = "16"

[[redirects]]
from = "/brew/"
to = "/.netlify/functions/brew"
status = 200
force = true
_generated_by_eleventy_serverless = "brew"

[[redirects]]
from = "https://troyvassalotti.netlify.com/*"
to = "https://www.troyv.dev/:splat"
status = 301
force = true

[[edge_functions]]
function = "now-playing"
path = "/music/"

[[edge_functions]]
function = "recent-listens"
path = "/music/"

[[edge_functions]]
function = "top-artists"
path = "/music/"

[[headers]]
for = "/*"

  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1"

[[plugins]]
package = "netlify-plugin-webmentions"

[[plugins]]
package = "netlify-plugin-cache"
