---
new_page_extension: md
auto_deploy: false
admin_path: src/admin
webhook_url: 
sections:
- type: heading
  label: Config
- type: document
  path: src/_data/nav.json
  label: Navigations
- type: heading
  label: Pages
- type: directory
  path: src/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: src/work
  label: Work
  create: all
  match: "**/*"
  templates:
  - work
- type: directory
  path: src/pages
  label: Misc. Pages
  create: all
  match: "**/*"
  templates:
  - misc-page
- type: document
  path: src/about/resume.11tydata.json
  label: Resume
- type: document
  path: src/about/index.md
  label: About/Now
- type: document
  path: src/music/index.11tydata.json
  label: Band Links
upload_dir: src/assets/img
public_path: "/assets/img"
front_matter_path: "./src/assets/img"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
